### ISSUE TITLE
Fornax Core as nuget package

### ISSUE THREAD

**Issue by kMutagene** [ionide/Fornax#123] opened 2023-03-05 08:31 UTC
It would be cool if the Fornax core package that contains the basic types and the HTML DSL could be published as library on nuget.
It would be easier to create packages that contain components for Fornax that way (currently, you have to include the compiled fornax dll in a package to do that)

**Comment by rdipardo** [comment] 2023-03-05 12:16
A (welcome) duplicate of https://github.com/ionide/Fornax/issues/70#issuecomment-1195843459

This will be necessary for the future distribution of [themes] and [template libraries], not to mention plugins. The early adopters out there are still relying on submodules, [fragile build configurations], and even [pushing assemblies to version control] :scream:

[themes]: https://github.com/ionide/Fornax/issues/71
[template libraries]: https://github.com/ionide/Fornax/issues/67
[fragile build configurations]: https://github.com/rdipardo/Fornax.Seo/wiki/FAQ#faq
[pushing assemblies to version control]: https://github.com/fsharp/fssf-website/issues/3#issue-637450862

**Comment by drewknab** [comment] 2023-03-06 17:18
Robert listed all the great reasons to make this happen. Is there a particularly compelling reason not to throw Fornax.Core into nuget?

**Comment by TheAngryByrd** [comment] 2023-03-07 15:45
https://www.nuget.org/packages/Fornax.Core/ is out

**Closed by TheAngryByrd** 2023-03-07 15:45 UTC

**Comment by kMutagene** [comment] 2023-03-07 17:44
Thank you!
